-- This file allow to write SQL commands that will be emitted in test and dev.
-- The commands are commented as their support depends of the database
-- insert into myentity (id, field) values(1, 'field-1');
-- insert into myentity (id, field) values(2, 'field-2');
-- insert into myentity (id, field) values(3, 'field-3');
-- alter sequence myentity_seq restart with 4;

INSERT INTO estado (nome, sigla)
VALUES ('Acre', 'AC'),
       ('Alagoas', 'AL'),
       ('Amapá', 'AP'),
       ('Amazonas', 'AM'),
       ('Bahia', 'BA'),
       ('Ceará', 'CE'),
       ('Distrito Federal', 'DF'),
       ('Espírito Santo', 'ES'),
       ('Goiás', 'GO'),
       ('Maranhão', 'MA'),
       ('Mato Grosso', 'MT'),
       ('Mato Grosso do Sul', 'MS'),
       ('Minas Gerais', 'MG'),
       ('Pará', 'PA'),
       ('Paraíba', 'PB'),
       ('Paraná', 'PR'),
       ('Pernambuco', 'PE'),
       ('Piauí', 'PI'),
       ('Rio de Janeiro', 'RJ'),
       ('Rio Grande do Norte', 'RN'),
       ('Rio Grande do Sul', 'RS'),
       ('Rondônia', 'RO'),
       ('Roraima', 'RR'),
       ('Santa Catarina', 'SC'),
       ('São Paulo', 'SP'),
       ('Sergipe', 'SE'),
       ('Tocantins', 'TO');


INSERT INTO cidade (nome, estado_id)
VALUES ('Palmas', 27),
       ('Anápolis', 9),
       ('Goiânia', 9),
       ('Araguaína', 27),
       ('Rio de Janeiro', 19),
       ('São Paulo', 25),
       ('Curitiba', 16),
       ('Porto Alegre', 21),
       ('Fortaleza', 6),
       ('Salvador', 5),
       ('Belo Horizonte', 13),
       ('Vitória', 8),
       ('Manaus', 4),
       ('Belém', 14),
       ('Recife', 17),
       ('Natal', 20),
       ('João Pessoa', 15),
       ('Maceió', 2),
       ('Aracaju', 26),
       ('Boa Vista', 23),
       ('Macapá', 3),
       ('São Luís', 10),
       ('Cuiabá', 11),
       ('Campo Grande', 12),
       ('Florianópolis', 24),
       ('Porto Velho', 22),
       ('Rio Branco', 1),
       ('Teresina', 18),
       ('Brasília', 7),
       ('Sobral', 6),
       ('Caxias do Sul', 21),
       ('Dourados', 12);